ClusterName=linux
SlurmctldHost=slurmctld
ProctrackType=proctrack/linuxproc
ReturnToService=1
SlurmdParameters=config_overrides
MaxNodeCount=100
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurm
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm
TaskPlugin=task/affinity
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
SchedulerType=sched/backfill
SelectType=select/cons_tres
AccountingStorageHost=slurmdbd
AccountingStorageType=accounting_storage/slurmdbd
JobCompLoc=/var/log/slurm/jobcomp.log
JobCompType=jobcomp/filetxt
JobAcctGatherFrequency=30
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log
AuthType=auth/munge
NodeSet=cpu_nodes Feature=cpu
PartitionName=cpu Nodes=cpu_nodes Default=YES MaxTime=INFINITE State=UP
